# Generated by Django 4.0.10 on 2024-02-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='another',
            new_name='author',
        ),
    ]
