# Generated by Django 4.0.10 on 2024-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
